site_name: Learning the Society
theme:
    name: material
    feature:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    langauge: en
    palette:
      - scheme: default
        toggle:
           icon: material/toggle-switch-off-outline
           name: Switch to dark mode
        accent: purple
      - scheme: slate
        toggle:
           icon: material/toggle-switch
           name: Switch to light mode
        accent: lime

extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/AlanBook
          
copyright:
  &copy 2023 <a href="https://github.com/AlanBook" target="_blank" rel="noopenner">AlanBook</a>
        
        